- name: Create ipam rir
  netbox.netbox.netbox_rir:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_api_token }}"
    validate_certs: false
    data:
      name: RFC 1918
      is_private: true
    state: present
