- name: Create ipam aggregate
  netbox.netbox.netbox_aggregate:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_api_token }}"
    validate_certs: false
    data:
      prefix: 10.0.0.0/8
      rir: RFC 1918
    state: present

- name: Create ipam aggregate
  netbox.netbox.netbox_aggregate:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_api_token }}"
    validate_certs: false
    data:
      prefix: 192.168.0.0/16
      rir: RFC 1918
    state: present

- name: Create ipam aggregate
  netbox.netbox.netbox_aggregate:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_api_token }}"
    validate_certs: false
    data:
      prefix: 172.16.0.0/12
      rir: RFC 1918
    state: present
