#SPDX-License-Identifier: MIT-0
---
# tasks file for ipam
- name: Include netbox_ipam_role
  ansible.builtin.import_tasks:
    file: ipam_role.yml

- name: Include netbox_ipam_role
  ansible.builtin.import_tasks:
    file: ipam_rir.yml

- name: Include netbox_ipam_role
  ansible.builtin.import_tasks:
    file: ipam_aggregate.yml

- name: Include netbox_ipam_tag
  ansible.builtin.import_tasks:
    file: ipam_tag.yml

- name: Include netbox_ipam_custom_field
  ansible.builtin.import_tasks:
    file: ipam_custom_field.yml

- name: Include netbox_ipam_prefix
  ansible.builtin.import_tasks:
    file: ipam_prefix.yml

